import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main book sidebar - explicitly listed to exclude stubborn tutorial folders
  bookSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Chapter 1: Foundations',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'chapter-1' }],
    },
    {
      type: 'category',
      label: 'Chapter 2: Mathematics',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'chapter-2' }],
    },
    {
      type: 'category',
      label: 'Chapter 3: Perception',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'chapter-3' }],
    },
    {
      type: 'category',
      label: 'Chapter 4: Control',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'chapter-4' }],
    },
    {
      type: 'category',
      label: 'Chapter 5: Learning',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'chapter-5' }],
    },
  ],
};

export default sidebars;
